// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/strider.h"
#include <Rcpp.h>

using namespace Rcpp;

// test
void test();
RcppExport SEXP _strider_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test();
    return R_NilValue;
END_RCPP
}
// test_row_sum
NumericVector test_row_sum(NumericMatrix& x);
RcppExport SEXP _strider_test_row_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test_row_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// test_col_sum
NumericVector test_col_sum(NumericMatrix& x);
RcppExport SEXP _strider_test_col_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test_col_sum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_strider_test", (DL_FUNC) &_strider_test, 0},
    {"_strider_test_row_sum", (DL_FUNC) &_strider_test_row_sum, 1},
    {"_strider_test_col_sum", (DL_FUNC) &_strider_test_col_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_strider(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
