// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/strider.h"
#include <Rcpp.h>

using namespace Rcpp;

// row_sums
NumericVector row_sums(const NumericMatrix& x);
RcppExport SEXP _strider_row_sums(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(row_sums(x));
    return rcpp_result_gen;
END_RCPP
}
// col_sums
NumericVector col_sums(const NumericMatrix& x);
RcppExport SEXP _strider_col_sums(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(col_sums(x));
    return rcpp_result_gen;
END_RCPP
}
// test_throw_equal
void test_throw_equal();
RcppExport SEXP _strider_test_throw_equal() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_throw_equal();
    return R_NilValue;
END_RCPP
}
// test_throw_distance1
int test_throw_distance1();
RcppExport SEXP _strider_test_throw_distance1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_throw_distance1());
    return rcpp_result_gen;
END_RCPP
}
// test_throw_distance2
int test_throw_distance2();
RcppExport SEXP _strider_test_throw_distance2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_throw_distance2());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_strider_row_sums", (DL_FUNC) &_strider_row_sums, 1},
    {"_strider_col_sums", (DL_FUNC) &_strider_col_sums, 1},
    {"_strider_test_throw_equal", (DL_FUNC) &_strider_test_throw_equal, 0},
    {"_strider_test_throw_distance1", (DL_FUNC) &_strider_test_throw_distance1, 0},
    {"_strider_test_throw_distance2", (DL_FUNC) &_strider_test_throw_distance2, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_strider(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
