# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call(`_strider_test`))
}

test_row_sum <- function(x) {
    .Call(`_strider_test_row_sum`, x)
}

test_col_sum <- function(x) {
    .Call(`_strider_test_col_sum`, x)
}

