# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast row sums
#' 
#' Demonstration of fast row and columns sums in C++
#' 
#' @param x a numeric matrix
#' 
#' @details A very efficient row summing algorithm that demonstrates
#' the use of the strided pointer concept. The \code{row_sum} algorithm is
#' roughly twice as fast as \code{\link{rowSums}}. The \code{col_sum} algorithm 
#' matches \code{\link{colSums}} for speed.
#'
#' @examples
#' row_sums(matrix(1:9, 3))
#' col_sums(matrix(1:9, 3))
#' 
#' @rdname sums
#' @export
row_sums <- function(x) {
    .Call(`_strider_row_sums`, x)
}

#' @rdname sums
#' @export
col_sums <- function(x) {
    .Call(`_strider_col_sums`, x)
}

test_throw_equal <- function() {
    invisible(.Call(`_strider_test_throw_equal`))
}

test_throw_distance1 <- function() {
    .Call(`_strider_test_throw_distance1`)
}

test_throw_distance2 <- function() {
    .Call(`_strider_test_throw_distance2`)
}

